Reverting Carlos' commit 899cfc7
This was giving me errors connecting:
AttributeError: 'Connector' object has no attribute 'omero_session_key'
Need to review this logic

Former-commit-id: 802bffa2b6c52d7582bdfe25c9aea7532fb7d2fd